let getShows = function() {
    return [
    { id: 'cowboybebop', title: 'Cowboy Bebop', synopsis: `Cocky Spike Spiegel and the crew of his spaceship, Bebop, an intrepid band of bounty hunters, land on Mars in the year 2071 chasing an enormous cash reward. The four-person team, also including looming cyborg Jet Black, fearless Faye Valentine and tech expert Edward, are in search of ex-military officer Vincent. The former hero has become a biological terrorist with an arsenal of devastating nano-bots that he'll let loose on Alba City on the night before Halloween if his demands aren't met.` },
    { id:'dragonball', title:'Dragon Ball', synopsis: `The series begins with a young monkey-tailed boy named Goku befriending a teenage girl named Bulma. Together they go on a quest to find the seven Dragon Balls (ドラゴンボール), which summons the dragon Shenron to grant the user one wish.`}, 
    { id: 'neongenesisevangelion', title:'Neon Genesis Evangelian',  synopsis: `The Evangelion series revolves around the organization NERV, using large mechas called Evangelions to combat monstrous beings called Angels. They are piloted by several of the main characters, including Shinji Ikari, Asuka Sohryu, and Rei Ayanami. While the initial episodes focus largely on religious symbols and specific references to the Bible, the later episodes tend to go deeper into the psyches of the characters, where it is learned that many of them have deep seated emotional and mental issues. Through the exploration of these issues, the show begins to question reality and the existences therein. Much of the series's content was based on Hideaki Anno's own clinical depression.`},
    { id: 'ruruonikenshin', title: 'Ruruoni Kenshin', synopsis: `In the early Meiji era, after participating in the Bakumatsu war as the assassin "Hitokiri Battōsai", Himura Kenshin wanders the countryside of Japan with a reverse blade katana, offering protection and aid to those in need as atonement for the murders he once committed.`},
    { id: 'schoolrumble', title: 'School Rumble',  synopsis: `A romance comedy centering on relationships between Japanese high school students, School Rumble focuses on a love triangle involving the series' two protagonists, Tenma Tsukamoto and Kenji Harima, and one of their classmates, Oji Karasuma. The series often discards realism in favor of comedic effect`},
    { id: 'yuyuhakusho', title:'Yu Yu Hakusho',  synopsis: `Yu Yu Hakusho follows Yusuke Urameshi, a 14-year-old street-brawling delinquent who, in an uncharacteristic act of altruism, is hit by a car and killed in an attempt to save a young boy by pushing him out of the way. ... Yusuke succeeds with the help of his friends Keiko Yukimura and Kazuma Kuwabara.`}
    ];
}
module.exports = getShows; 